# Generated by Django 2.0.3 on 2018-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogsPost',
            new_name='Article',
        ),
    ]
